
# Preliminaries


Each method is listed
in Table 1 with a graphical summary provided in Figure \ref{fig:overview}.

\input{methodsTable.tex}

* \textcolor{blue}{Normalized cross correlation (NCC):  $1 - \Big\langle  \frac{I - \mu_I}{ \| I - \mu_I \|_2}, \frac{J - \mu_J}{ \| J - \mu_J \|_2}  \Big\rangle$}
* \textcolor{blue}{Mean squared intensity error (MSQ): $\| I - J \|^2$}
* \textcolor{blue}{L1 or photometric difference: $\| I - J \|$}
* \textcolor{blue}{Mean squared transformation error (MSQ$_T$): $\| T_I - T_J\|^2$}
* \textcolor{blue}{Normalized mutual information (NMI)} [@Rueckert:1999aa;@Pluim:2003aa]\textcolor{blue}{: $\frac{H(I) + H(J)}{H(I,J)}$ where $H$ is the Shannon Entropy.}
* \textcolor{blue}{Structural similarity index (SSIM)} [@Wang:2004aa]\textcolor{blue}{:  $\frac{(2\mu_I\mu_J + c_1)(2\sigma_{IJ} + c_2)}{(\mu_I^2 + \mu_J^2 + c_1)(\sigma_I^2 + \sigma_J^2 + c_2)}$}
* \textcolor{blue}{Local cross correlation (LCC)} [@Avants:2011aa]\textcolor{blue}{: $\frac{\sum_{x_i \in \mathcal{N}} \left( \left( I(x_i) - \mu_{I(x)} \right) \left( J(x_i) - \mu_{J(x)} \right) \right)^2}{\sum_{x_i \in \mathcal{N}} \left( I(x_i) - \mu_{I(x)} \right)^2 \sum_{x_i \in \mathcal{N}} \left( J(x_i) - \mu_{J(x)} \right)^2}$}

